name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: pnpm/action-setup@v2.1.0
        with:
          run_install: true
          version: 6.0.2
      - name: Run Tests
        run: pnpm test
